### ISSUE TITLE
A way to skip conversion for libraries in WEB-INF/lib

### ISSUE THREAD

**Issue by ShamithaSIlva** [apache/tomcat-jakartaee-migration#18]
Hi first of all, thanks for the efforts for this plugin. This is not an issue but asking a way to skip conversion of libraries inside a war (WEB-INF/lib). Because libraries do not get changed often so we can save time on conversion between builds (After converting for the first time). So when deployed, old libraries can be manually copied and replaced on the server.

**Comment by markt-asf** [comment]
This is already implemented. Use the `-exclude` option on the command line or `Migration.addExclude(String)` if using the API.

Note that there is also an Ant Task to perform the migration during the build process and all the migrations will work on both source and compiled code. Between them you have lots of options for how you structure things so the process works best for you.
