### ISSUE TITLE
How can I add .groovy file support that do not get converted to .class files

### ISSUE THREAD

**Issue by ShamithaSIlva** [apache/tomcat-jakartaee-migration#19]
I have Groovy files having .groovy extensions that do not get compiled to .class file even after deployment. But they still have text based entries on those files like: import javax.servlet.http.HttpServletResponse.

Where should I change to add support for such files?

Thanks

**Comment by markt-asf** [comment]
That will need a code change. Longer term we might want to think about making this more configurable. For now, give me a few minutes and I'll have a snapshot build you can test...

**Comment by rmaucher** [comment]
Ideally, it has to be done magically [this is mandatory for the Tomcat auto deployment migration to work, since there's very little room for configuration] but this looks hard.

**Comment by markt-asf** [comment]
Latest 1.0.1-SNAPSHOT here has a f ix you can test:
https://repository.apache.org/content/repositories/snapshots/

Note: This is NOT an official ASF release. It is provided solely for the purposes of testing this fix. Use it at your own risk. If you want to update the JAR in Tomcat 10 that does this migration at deployment time you want the shaded JAR.

**Comment by ShamithaSIlva** [comment]
> Latest 1.0.1-SNAPSHOT here has a f ix you can test:
> https://repository.apache.org/content/repositories/snapshots/
> 
> Note: This is NOT an official ASF release. It is provided solely for the purposes of testing this fix. Use it at your own risk. If you want to update the JAR in Tomcat 10 that does this migration at deployment time you want the shaded JAR.

Thanks will try this I thought it should work if I add .grovvy in supportedExtensions in TextConverter file. Will reply if this works with this snapshot

**Comment by rmaucher** [comment]
Yes, just add your extension here:
https://github.com/apache/tomcat-jakartaee-migration/blob/master/src/main/java/org/apache/tomcat/jakartaee/TextConverter.java#L37

**Comment by ShamithaSIlva** [comment]
> Yes, just add your extension here:
> https://github.com/apache/tomcat-jakartaee-migration/blob/master/src/main/java/org/apache/tomcat/jakartaee/TextConverter.java#L37

Yes I suspected here and added the line let's see. thanks

**Comment by ShamithaSIlva** [comment]
Adding the extension on the file works:
https://github.com/apache/tomcat-jakartaee-migration/blob/master/src/main/java/org/apache/tomcat/jakartaee/TextConverter.java#L37

Thanks a lot guys!
