### ISSUE TITLE
facing issue while migrating the war

### ISSUE THREAD

**Issue by mohiniagrawal** [apache/tomcat-jakartaee-migration#21]
I am trying to deploy a war in which there is a class extending javax.servet.ServletContextListener and overriding method contextIntialized(javax.servlet.ServletContextEvent) method.
After migrating the war using the tomcat-jakartaee-migration tool, the following issue is resolved.
        **java.lang.NoClassDefFoundError: javax/servlet/ServletContextListener**

But now it is looking for overriden method contextIntialized(jakarta.servlet.ServletContextEvent) but in actual code it is contextIntialized(javax.servlet.ServletContextEvent). 
Since the migration tool is in progress now, I wanted to ask if there is a plan to handle such a scenario as well while migration or it should be handled by application developers themselves?

And if there is a plan to handle such a scenario then may I know the expected timeline it is planned for? 

Thanks

**Comment by martin-g** [comment]
I believe this should just work.
Please create a demo application at Github and share it with us.

**Comment by markt-asf** [comment]
No response for over 3 weeks. Assuming root cause was user error.
