### ISSUE TITLE
Migrates packages that should not be migrated

### ISSUE THREAD

**Issue by jpschewe** [apache/tomcat-jakartaee-migration#22]
I'm using javax.annotation and the tool rewrote these to jakarta.annotation.

**Comment by markt-asf** [comment]
This is by design.

**Comment by jpschewe** [comment]
You exclude other javax namespaces, why not javax.annotation?

**Comment by jpschewe** [comment]
Ahh, I see that both jsr305 and Tomcat used the javax.annotation namespace.
