### ISSUE TITLE
Removing signature from JAR file with JCE providers leads to SecurityException

### ISSUE THREAD

**Issue by smarkwal** [apache/tomcat-jakartaee-migration#3]
If this migration tool removes the cryptographic signature from a JAR file which contains JCE providers (e.g., Bouncy Castle), Java refuses to use these providers afterward:

```
java.lang.SecurityException: JCE cannot authenticate the provider BC
[...]
Caused by: java.util.jar.JarException: file:/tmp/[...]/bcprov-ext-jdk15on-1.65.jar has unsigned entries - org/bouncycastle/LICENSE.class
```

I see two possible solutions:

1. If the classes in a JAR file do not have dependencies on Java EE classes, the JAR file is not touched by this migration tool. This means that the signature remains intact.
2. If a JAR file contains JCE providers, it is not touched by this migration tool. Instead, a warning is printed.

I think that solution 1 is easier to implement, since it does not require special knowledge about JCE providers (or other features which require signed JAR files).

Bouncy Castle's main JAR file does not have dependencies on any Java EE classes. This means that both solutions would work for it.

**Comment by ebourg** [comment]
Leaving JAR files unmodified if they don't reference any EE class sounds like the best solution to me. This will probably require buffering the files in memory.

**Comment by rmaucher** [comment]
I think users should probably use scripting to exclude problem JARs from the migration.

Trying to do too much would lead to more problems, here a likely excessive memory use [there is the same problem with SB which wants some uncompressed JARs, also not doable without full load in memory]. This tool is IMO better if it stays simple.

**Comment by smarkwal** [comment]
How about adding a command line option to exclude certain JAR files from getting migrated? It adds just a little bit of complexity in how to use the tool, but it has no impact on memory usage. And it is maybe useful in other scenarios as well.

**Comment by rmaucher** [comment]
Yes, a resource filtering pattern or some kind could be a good add with plenty of uses.
Still copy out and in should work and would likely be easier for you to do with your JCE JAR.

**Comment by ebourg** [comment]
> Trying to do too much would lead to more problems, here a likely excessive memory use.

What is an excessive memory usage? A typical jar easily fits in the heap allocated by default to the JVM. This tool is mainly used at build time on beefy machines, I don't think the memory usage is really a concern.

> How about adding a command line option to exclude certain JAR files from getting migrated?

Good idea, something like an `--exclude` option with a glob parameter that could be repeated many times.

**Comment by ebourg** [comment]
Also `bcprov*.jar` could be excluded by default.
