### ISSUE TITLE
Exception occured while sending Websocket Message and the session is being closed.

### ISSUE THREAD

**Issue by Karthikeyan021298** [apache/tomcat-jakartaee-migration#31]
Hi, 

I am trying to send the Message from the Websocket Server using "session.getBasicRemote().sendText("message");" , I got the IO exception message" The current thread was interrupted while waiting for a blocking send to complete "  and the Websocket Session being closed due to the exception.

This Issue is happening while I am trying to run multiple threads parallely to send the message on the same session object,  Note: the method to send the Wesocket Message is Synchronised, still I am getting the Exception.

Tomcat Version used- 8.5.11.

Can anyone please help me to solve this issue. Thanks in advance.

Regards,
Karthikeyan

**Comment by markt-asf** [comment]
Wrong project. And support questions belong on the users mailing list, not in the issue tracker.
https://tomcat.apache.org/lists.html#tomcat-users
