### ISSUE TITLE
Does this project work in a spring 5 project?

### ISSUE THREAD

**Issue by ahksdfhkjh** [apache/tomcat-jakartaee-migration#35]
I assume spring 5 project is not supported, since below codes,

https://github.com/apache/tomcat-jakartaee-migration/blob/d8b33d3d7a055a01d0fcfc8c9dc4ddd2bc514125/src/main/java/org/apache/tomcat/jakartaee/Migration.java#L85-L88

Is this true?

**Comment by markt-asf** [comment]
No. Those JARs are excluded because they are known not to contain any classes that require conversion. The exclusion is a performance optimisation.
