### ISSUE TITLE
Download of Release

### ISSUE THREAD

**Issue by Horcrux7** [apache/tomcat-jakartaee-migration#4]
Is there any download of the released version? For example in bintray or maven repository. I was not able to find it.

**Comment by martin-g** [comment]
There is no such at the moment. You have to build it locally.

**Comment by Horcrux7** [comment]
Ok, I will wait until a binary version is available.

**Comment by ChristopherSchultz** [comment]
This is intended to be a tool used by developers. Anyone qualified to use this tool should also be qualified to build it from source. Don't expect a binary release anytime soon.

**Comment by Horcrux7** [comment]
A software developer has the source code of its projects and does not need your tool. It look for me more as a tool for administrators. So it might be.

A tool of which the developers do not bother to spend time uploading a binary with the release (about a minute here on Github) does not seem to be of much value in the opinion of these developers. Then as a tester you don't need to bother to test it. Thanks for the clarification.

**Comment by martin-g** [comment]
Since this tool is not supposed to be used as a (Maven/Gradle) dependency there is no really point in uploading it to Maven Central.
But we can publish GitHub releases - https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/managing-releases-in-a-repository.

WDYT ?

**Comment by markt-asf** [comment]
We'd need to go through the ASF release process (not arduous but requires a little setting up as this is a new deliverable for the Tomcat project) and the primary release channel would need to be via the Tomcat website and the ASF mirror system. Additional channels, such as GitHub, could be added fairly easily if required.
I can see this module being used as a component in other tools so Maven Central may make sense as well.
