### ISSUE TITLE
Workaround for JDK-8303866 makes migrated jar incompatible with latest JDK releases

### ISSUE THREAD

**Issue by DanielThomas** [apache/tomcat-jakartaee-migration#48]
The zip validation changes for [JDK-8302483](https://www.oracle.com/java/technologies/javase/17-0-8-relnotes.html#JDK-8302483) causes failures to load jars output by the migration tool:

```
lombok-1.18.28.jar; Invalid CEN header (invalid zip64 extra data field size)
```

The problem appears to be the workaround for JDK-8303866, the field removal appears to cause the problem:

https://github.com/apache/tomcat-jakartaee-migration/blob/4b767e426dfa1cf4b565eb328d51fe1ddb043825/src/main/java/org/apache/tomcat/jakartaee/Migration.java#L317C40-L320

We're currently using in-memory transforms as a workaround, but because we're using the tool in https://github.com/nebula-plugins/gradle-jakartaee-migration-plugin/ and they run in parallel, that can lead to heap utilization issues in builds.

These Lombok jars are the only ones we've run into trouble with.

**Comment by markt-asf** [comment]
I can't repeat this. Please provide:
- the command used to convert lombok-1.18.28.jar using version 1.0.7 of the migration tool
- the simplest Java code that demonstrates the problem with the result of the migration

**Comment by DanielThomas** [comment]
Some improvements got made to this mitigation in later JDK releases, due to false positives in the detection, so I think this has been addressed upstream.
