### ISSUE TITLE
Request to support ear file type as archive file

### ISSUE THREAD

**Issue by sammyhk** [apache/tomcat-jakartaee-migration#49]
Now the migration tools only recognize jar, war, zip as archive file (https://github.com/apache/tomcat-jakartaee-migration/blob/4b767e426dfa1cf4b565eb328d51fe1ddb043825/src/main/java/org/apache/tomcat/jakartaee/Migration.java#L416), request to add ear as archive file.

**Comment by markt-asf** [comment]
Fixed via #50
