### ISSUE TITLE
ability to ignore file extensions?

### ISSUE THREAD

**Issue by darmbrust** [apache/tomcat-jakartaee-migration#5]
I've been using this tool, to try out an entire stack with these changes, and we have one webapp which is a JRuby application.

Using this tool on the war file produced by our JRuby build, results in a failure:

Migrating Jar entry [WEB-INF/gems/gems/rubyzip-1.2.2/test/data/globTest/foo/]
Migrating stream [WEB-INF/gems/gems/rubyzip-1.2.2/test/data/globTest/foo/]
Migrating Jar entry [WEB-INF/gems/gems/rubyzip-1.2.2/test/data/globTest/foo.txt]
Migrating stream [WEB-INF/gems/gems/rubyzip-1.2.2/test/data/globTest/foo.txt]
Migrating Jar entry [WEB-INF/gems/gems/rubyzip-1.2.2/test/data/globTest/foo/bar/]
Migrating stream [WEB-INF/gems/gems/rubyzip-1.2.2/test/data/globTest/foo/bar/]
Migrating Jar entry [WEB-INF/gems/gems/rubyzip-1.2.2/test/data/globTest/foo/bar/baz/]
Migrating stream [WEB-INF/gems/gems/rubyzip-1.2.2/test/data/globTest/foo/bar/baz/]
Migrating Jar entry [WEB-INF/gems/gems/rubyzip-1.2.2/test/data/globTest/foo/bar/baz/foo.txt]
Migrating stream [WEB-INF/gems/gems/rubyzip-1.2.2/test/data/globTest/foo/bar/baz/foo.txt]
Migrating Jar entry [WEB-INF/gems/gems/rubyzip-1.2.2/test/data/globTest/food.txt]
Migrating stream [WEB-INF/gems/gems/rubyzip-1.2.2/test/data/globTest/food.txt]
Migrating Jar entry [WEB-INF/gems/gems/rubyzip-1.2.2/test/data/gpbit3stored.zip]
Migrating archive [WEB-INF/gems/gems/rubyzip-1.2.2/test/data/gpbit3stored.zip]
Error performing migration

No additional details are given on the reason for the failure.
Still looking into why the rubyzip gem has piles of test data in it... but that aside, it would be nice to tell this tool to ignore .txt and .zip files...

**Comment by darmbrust** [comment]
For reference, this is the zip file the tool is failing on:
https://github.com/rubyzip/rubyzip/blob/master/test/data/gpbit3stored.zip

From the context of the file its failing on, I'm guessing something isn't handling the general purpose bit flag properly when it is encountered:
https://en.wikipedia.org/wiki/Zip_(file_format)#Local_file_header

**Comment by markt-asf** [comment]
Fix, primarily in fc2245dd, with the addition of an option that processes Zip archives in memory rather than via streaming.
