### ISSUE TITLE
How can I know the migrated jar is actually "touched" or not after running MigrationCLI

### ISSUE THREAD

**Issue by zoumuzou** [apache/tomcat-jakartaee-migration#51]
Hi,

I'm using MigrationCLI.migrate to do jar to jar mutation.

I'd like to know whether the jar is modified or not after CLI. 
Since I may apply different policy against this, like "keep the original jar" or "upload the transformed jar".

I guess the migration process must left some foot prints to indicate the which classes are modified.
If not, can I do checksum against original jar and transformed jar to determine whether it's touched or not?

Thanks in advance!

Leon

**Comment by markt-asf** [comment]
There is no output that explicitly indicates if the JAR has been modified or not.

While a hash of the file not changing can be taken to confirm that no changes were required, the converse is not true. It is possible that the migration tool will modify the structure of a JAR even if no actual migration is performed.

**Comment by zoumuzou** [comment]
OK, thanks a lot!
