### ISSUE TITLE
Unable to install Tomcat 9 - **"Package 'tomcat9' has no installation candidate"** || Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by dipualnur** [apache/tomcat-jakartaee-migration#56]
I'm trying to install Tomcat 9 on my Ubuntu system using `*

`sudo apt-get install tomcat9`

but I keep running into the following error:

> monirul@nitacl-Veriton-Series:~$ sudo apt-get install tomcat9 Reading package lists... Done Building dependency tree... Done Reading state information... Done Package tomcat9 is not available, but is referred to by another package. This may mean that the package is missing, has been obsoleted, or is only available from another source E: Package 'tomcat9' has no installation candidate

Here's what I've tried so far:

`sudo apt update
`Searching for alternative package names (e.g., tomcat9.0, tomcat-9) using apt-cache search tomcat

System Information: Ubuntu version: 24.04 LTS Noble Numbat 
Architecture: LAMP

Could anyone please point me in the right direction? Is there a specific repository I need to enable or a different approach to installing Tomcat 9?

**Thanks in advance for your help!**

**Comment by slovdahl** [comment]
In general, I don't think is the right place for Ubuntu-specific package issues. For Ubuntu-specific package questions/issues, you should use https://bugs.launchpad.net instead.

That said, I happen to know the answer: Tomcat 9 is not packaged for Ubuntu 24.04, only Tomcat 10 is. You can use e.g. https://packages.ubuntu.com to find out which packages are packaged for a specific Ubuntu version.

I don't know of any repository that would provide Tomcat 9 on Ubuntu 24.04. You probably need to download it as .tar.gz files from https://tomcat.apache.org/download-90.cgi

**Comment by markt-asf** [comment]
For help with Ubuntu, you need to contact Ubuntu support.
