### ISSUE TITLE
Transforming entity-mappings xml files

### ISSUE THREAD

**Issue by AnishaKabir** [apache/tomcat-jakartaee-migration#61]
I'm attempting to use this tool to transform an entity-mappings xml file:

```
<?xml version="1.0" encoding="UTF-8"?>
<entity-mappings xmlns="http://java.sun.com/xml/ns/persistence/orm" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://java.sun.com/xml/ns/persistence/orm http://java.sun.com/xml/ns/persistence/orm_1_0.xsd" version="1.0">
...
```

When running the tomcat migration tool with logging it shows that the file was evaluated, but no modifications were made. Expecting it to be converted as such:

```
<?xml version="1.0" encoding="UTF-8"?>
<entity-mappings xmlns="https://jakarta.ee/xml/ns/persistence/orm" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://jakarta.ee/xml/ns/persistence/orm https://jakarta.ee/xml/ns/persistence/orm_3_0.xsd" version="3.0">
...
```

Is such a use case intended to be supported?

**Comment by markt-asf** [comment]
Is such a transformation necessary? I'm not too familiar with the Jakarta Persistence specification but in the specifications I am familiar with configuration files using the older Java EE schema are still supported. For example, it is an explicit requirement of the Servlet specification that all older versions of web.xml are supported.

**Comment by mattnelson** [comment]
Turns out it was not necessary to transform those files. We had previously manually updated the file while working through some issues, and incorrectly made the assumption that it was the fix.

Your comment and the readme(we missed this detail) confirms this well.

https://github.com/apache/tomcat-jakartaee-migration#differences-between-java-ee-8-and-jakarta-ee-9
> Note: It is not necessary to migrate any references to XML schemas. The schemas don't directly reference javax packages and Jakarta EE 9 will continue to support the use of schemas from Java EE 8 and earlier.

**Comment by markt-asf** [comment]
Thanks for the confirmation. I'll close this issue.
