### ISSUE TITLE
Do not migrate javax.xml.namespace

### ISSUE THREAD

**Issue by rmannibucau** [apache/tomcat-jakartaee-migration#9]
Execute the CLI on javax.xml.xpath.XPathConstants and you get jakarta namespace whereas it should stay javax.
Guess the EEProfile thing will need to move to something configurable since it only handles very particular cases today.

**Comment by ebourg** [comment]
I'm unable to reproduce this issue, I've added `javax.xml.xpath.XPathConstants` to the test case in f393d76 and it passed for both profiles.

**Comment by rmannibucau** [comment]
The test does not test what i described.
Issue is that the fields of this class are qname so handled by ee regex so at runtile you get a nosuchfielderror (use a classloader to list field in javax and jakarta lands).
Can help if you spend too much time on it - thought it was easy originally but can be faster to do a pr ;).

**Comment by rmannibucau** [comment]
Created https://github.com/apache/tomcat-jakartaee-migration/pull/10 to illustrate and fix the case I got on primefaces 7.0.

Side note: it is a partial fix (in regards of the theory). I'd love we add a CUSTOM profile which would be configured from system properties. Config would be includes/excludes but should also be OpCode+related data, this part is a but harder to do simple enough to stay usable so didn't give a try yet but something to keep in mind if we encounter too much this kind of issue (I'm expecting it with transaction too since SE has part of XA API).

**Comment by ebourg** [comment]
Is there an EE API that uses the javax.xml.namespace package?

**Comment by rmannibucau** [comment]
@ebourg I'm not sure to be honest, it is not in ee bundle jar but https://raw.githubusercontent.com/eclipse-ee4j/jakartaee-platform/master/namespace/mappings.adoc makes it mapped to jakarta.xml.namespace (https://github.com/jakartaee/jakarta.ee/issues/592). Not sure it is just outdated or not. Happy if the fix is to drop namespace from the regex too.

**Comment by ebourg** [comment]
I'm tempted to think the mapping document is wrong. I'm going to remove the `javax.xml.namespace` package from the EE profile. If there is an EE API using this package we can whitelist the QName class which belongs to Java SE.
